version: '3'

services:
  backend:
    build:
      context: ./api
    container_name: go_backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
