# 使用 Node.js 作为基础镜像
FROM node:14.15.5-alpine3.10 AS builder

# 设置工作目录
WORKDIR /app

# 将宿主机的 package.json 和 package-lock.json 文件复制到容器内
COPY package*.json ./

# 安装依赖
RUN npm install

# 将宿主机的当前目录下的所有文件复制到容器的 /app 目录下
COPY . .

# 构建生产环境代码
RUN npm run build

# 使用更轻量级的基础镜像
FROM nginx:1.19.7-alpine

# 将构建的生产环境代码复制到 Nginx 中
COPY --from=builder /app/dist /usr/share/nginx/html

# 复制自定义 Nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 暴露应用需要的端口
EXPOSE 8888

# 容器启动命令
CMD ["nginx", "-g", "daemon off;"]
